In [ ]:
import numpy as np
import pandas as pd

## QUES 1

In [ ]:
customer=pd.read_csv("/content/AWCustomers.csv")

In [ ]:
customer.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [ ]:
customer=customer.drop("Title", axis=1)

In [ ]:
customer = customer.drop("Suffix", axis=1)
customer = customer.drop("AddressLine2", axis=1)
customer = customer.drop("LastUpdated", axis=1)
customer = customer.drop("Education", axis=1)

In [ ]:
updated_customer=customer

In [ ]:
updated_customer.head()

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,Chad,C,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,1987-11-13,Clerical,M,M,1,3,0,1,81916
1,13249,Ryan,NaN,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,1972-07-21,Clerical,M,M,1,2,1,2,81076
2,29350,Julia,NaN,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,1985-11-09,Clerical,F,S,0,3,0,0,86387
3,13503,Theodore,NaN,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,1977-10-18,Skilled Manual,M,M,1,2,1,2,61481
4,22803,Marshall,J,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,1975-02-05,Skilled Manual,M,S,1,1,0,0,51804

In [ ]:
updated_customer.describe()

,CustomerID,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
count,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000
mean,20241.987092,0.610588,1.270301,0.338162,0.850389,72754.779642
std,5336.332731,0.487630,0.913989,0.568957,0.927315,30686.014313
min,11000.000000,0.000000,0.000000,0.000000,0.000000,25435.000000
25%,15621.000000,0.000000,1.000000,0.000000,0.000000,53312.000000
50%,20248.000000,1.000000,1.000000,0.000000,0.000000,61851.000000
75%,24863.000000,1.000000,2.000000,1.000000,2.000000,87410.000000
max,29483.000000,1.000000,5.000000,3.000000,3.000000,139115.000000

In [ ]:
updated_customer.describe(include='all')

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
count,18361.000000,18361,10572,18361,18361,18361,18361,18361,18361,18361,18361,18361,18361,18361,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000
unique,NaN,670,44,375,12742,269,54,6,323,8836,8230,5,2,2,NaN,NaN,NaN,NaN,NaN
top,NaN,Katherine,A,Diaz,AttachÃ© de Presse,London,California,United States,98168,1 (11) 500 555-0118,1987-05-14,Skilled Manual,M,M,NaN,NaN,NaN,NaN,NaN
freq,NaN,97,1287,209,17,420,4410,7770,212,204,11,6059,9287,9947,NaN,NaN,NaN,NaN,NaN
mean,20241.987092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.610588,1.270301,0.338162,0.850389,72754.779642
std,5336.332731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.487630,0.913989,0.568957,0.927315,30686.014313
min,11000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,25435.000000
25%,15621.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,0.000000,53312.000000
50%,20248.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,0.000000,61851.000000
75%,24863.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2.000000,1.000000,2.000000,87410.000000
max,29483.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,5.000000,3.000000,3.000000,139115.000000

In [ ]:
updated_customer=updated_customer.drop("PhoneNumber", axis=1)

In [ ]:
updated_customer.tail()

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
18356,25414,Grace,C,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,1990-11-11,Skilled Manual,F,M,0,1,0,2,52953
18357,11459,Tasha,NaN,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1992-10-13,Skilled Manual,F,S,0,2,0,0,60992
18358,12160,Jaclyn,NaN,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,1983-11-24,Skilled Manual,F,S,0,2,0,0,51859
18359,14353,Erin,I,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,1995-06-15,Clerical,F,S,0,0,0,0,87177
18360,16676,Amanda,NaN,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,1986-03-26,Professional,F,M,1,2,0,0,136856

In [ ]:
updated_customer=updated_customer.drop(["MiddleName", "LastName", "FirstName"], axis=1)

In [ ]:
updated_customer.head()

,CustomerID,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1987-11-13,Clerical,M,M,1,3,0,1,81916
1,13249,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,1972-07-21,Clerical,M,M,1,2,1,2,81076
2,29350,1774 Tice Valley Blvd.,West Covina,California,United States,91791,1985-11-09,Clerical,F,S,0,3,0,0,86387
3,13503,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1977-10-18,Skilled Manual,M,M,1,2,1,2,61481
4,22803,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1975-02-05,Skilled Manual,M,S,1,1,0,0,51804

In [ ]:
updated_customer.to_csv("AWUpdated.csv")

## Ques 2

In [ ]:
pd.isna(updated_customer).head()

,CustomerID,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
updated_customer.dropna()

,CustomerID,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1987-11-13,Clerical,M,M,1,3,0,1,81916
1,13249,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,1972-07-21,Clerical,M,M,1,2,1,2,81076
2,29350,1774 Tice Valley Blvd.,West Covina,California,United States,91791,1985-11-09,Clerical,F,S,0,3,0,0,86387
3,13503,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1977-10-18,Skilled Manual,M,M,1,2,1,2,61481
4,22803,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1975-02-05,Skilled Manual,M,S,1,1,0,0,51804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,6627 Camelback Ct.,Coronado,California,United States,92118,1990-11-11,Skilled Manual,F,M,0,1,0,2,52953
18357,11459,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1992-10-13,Skilled Manual,F,S,0,2,0,0,60992
18358,12160,4364 Viera Avenue,Beaverton,Oregon,United States,97005,1983-11-24,Skilled Manual,F,S,0,2,0,0,51859
18359,14353,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,1995-06-15,Clerical,F,S,0,0,0,0,87177
18360,16676,7870 Orangewood Dr.,Grossmont,California,United States,91941,1986-03-26,Professional,F,M,1,2,0,0,136856

In [ ]:
updated_customer['Gender'] = updated_customer['Gender'].replace({'M': 1, 'F': 0})
updated_customer.head()

,CustomerID,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1987-11-13,Clerical,1,M,1,3,0,1,81916
1,13249,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,1972-07-21,Clerical,1,M,1,2,1,2,81076
2,29350,1774 Tice Valley Blvd.,West Covina,California,United States,91791,1985-11-09,Clerical,0,S,0,3,0,0,86387
3,13503,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1977-10-18,Skilled Manual,1,M,1,2,1,2,61481
4,22803,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1975-02-05,Skilled Manual,1,S,1,1,0,0,51804

In [ ]:
updated_customer['MaritalStatus'] = updated_customer['MaritalStatus'].replace({'M': 1, 'S': 0})
updated_customer.head()

,CustomerID,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1987-11-13,Clerical,1,1,1,3,0,1,81916
1,13249,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,1972-07-21,Clerical,1,1,1,2,1,2,81076
2,29350,1774 Tice Valley Blvd.,West Covina,California,United States,91791,1985-11-09,Clerical,0,0,0,3,0,0,86387
3,13503,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1977-10-18,Skilled Manual,1,1,1,2,1,2,61481
4,22803,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1975-02-05,Skilled Manual,1,0,1,1,0,0,51804

In [ ]:

updated_customer=updated_customer.drop("CountryRegionName", axis=1)
updated_customer=updated_customer.drop("AddressLine1", axis=1)
updated_customer.head()

,CustomerID,City,StateProvinceName,PostalCode,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,Wollongong,New South Wales,2500,Clerical,1,1,1,3,0,1,81916
1,13249,Shawnee,British Columbia,V9B 2C3,Clerical,1,1,1,2,1,2,81076
2,29350,West Covina,California,91791,Clerical,0,0,0,3,0,0,86387
3,13503,Liverpool,England,L4 4HB,Skilled Manual,1,1,1,2,1,2,61481
4,22803,Werne,Nordrhein-Westfalen,59368,Skilled Manual,1,0,1,1,0,0,51804

In [ ]:
updated_customer=updated_customer.drop("PostalCode", axis=1)
updated_customer.head()

,CustomerID,City,StateProvinceName,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,21173,Wollongong,New South Wales,Clerical,1,1,1,3,0,1,81916
1,13249,Shawnee,British Columbia,Clerical,1,1,1,2,1,2,81076
2,29350,West Covina,California,Clerical,0,0,0,3,0,0,86387
3,13503,Liverpool,England,Skilled Manual,1,1,1,2,1,2,61481
4,22803,Werne,Nordrhein-Westfalen,Skilled Manual,1,0,1,1,0,0,51804

In [ ]:
encoded_data=pd.get_dummies(updated_customer)

In [ ]:
encoded_data.head()

,CustomerID,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,City_Ballard,City_Baltimore,...,StateProvinceName_Victoria,StateProvinceName_Virginia,StateProvinceName_Washington,StateProvinceName_Wyoming,StateProvinceName_Yveline,Occupation_Clerical,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
0,21173,1,1,1,3,0,1,81916,False,False,...,False,False,False,False,False,True,False,False,False,False
1,13249,1,1,1,2,1,2,81076,False,False,...,False,False,False,False,False,True,False,False,False,False
2,29350,0,0,0,3,0,0,86387,False,False,...,False,False,False,False,False,True,False,False,False,False
3,13503,1,1,1,2,1,2,61481,False,False,...,False,False,False,False,False,False,False,False,False,True
4,22803,1,0,1,1,0,0,51804,False,False,...,False,False,False,False,False,False,False,False,False,True

## Ques 3

In [54]:
def jaccard_similarity(set1, set2):
    set1 = set(set1)
    set2 = set(set2)

    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))

    return intersection / union if union != 0 else 0  
set1 = encoded_data.MaritalStatus
set2 = encoded_data.NumberCarsOwned
similarity = jaccard_similarity(set1, set2)
print("Jaccard Similarity:", similarity)

Jaccard Similarity: 0.3333333333333333

In [53]:
from numpy.linalg import norm
A = encoded_data.NumberCarsOwned
B = encoded_data.TotalChildren
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", cosine)

Cosine Similarity: 0.5617361741434632

In [59]:
encoded_data.corr()

,CustomerID,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,City_Ballard,City_Baltimore,...,StateProvinceName_Victoria,StateProvinceName_Virginia,StateProvinceName_Washington,StateProvinceName_Wyoming,StateProvinceName_Yveline,Occupation_Clerical,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
CustomerID,1.000000,0.013270,-0.071044,-0.029199,-0.012101,-0.039706,-0.071245,-0.029423,-0.000103,-0.009815,...,-0.008878,-0.002369,-0.002599,-0.007064,0.003103,-0.006030,-0.008868,0.024769,-0.022005,0.005141
Gender,0.013270,1.000000,0.042809,0.009935,0.003541,0.014645,0.030360,-0.000354,0.003814,0.007295,...,0.014384,0.007295,-0.000025,-0.000121,0.004646,-0.000735,-0.013094,0.011222,0.004709,-0.001308
MaritalStatus,-0.071044,0.042809,1.000000,0.442841,0.051823,0.471534,0.750911,0.048784,-0.000538,0.006788,...,0.002234,-0.008024,0.021952,0.009599,-0.040338,0.001439,0.037294,-0.014242,0.028880,-0.035670
HomeOwnerFlag,-0.029199,0.009935,0.442841,1.000000,0.209787,0.368459,0.578197,0.356243,-0.001685,-0.009241,...,-0.005626,0.005894,0.033265,0.008335,-0.039363,0.040706,0.190383,-0.213904,0.224440,-0.142416
NumberCarsOwned,-0.012101,0.003541,0.051823,0.209787,1.000000,0.020393,0.030430,0.477300,0.012739,-0.002183,...,0.003526,0.005892,0.019383,0.008333,-0.009991,0.183281,0.242365,-0.379733,0.203863,-0.163579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Occupation_Clerical,-0.006030,-0.000735,0.001439,0.040706,0.183281,0.003446,0.007238,0.171413,-0.000609,0.013022,...,0.005242,0.013022,0.020892,-0.005916,-0.009870,1.000000,-0.243346,-0.269063,-0.175290,-0.397754
Occupation_Management,-0.008868,-0.013094,0.037294,0.190383,0.242365,0.013343,0.007872,0.487918,-0.021001,-0.003169,...,0.002535,-0.003169,-0.002220,-0.004481,-0.014029,-0.243346,1.000000,-0.203833,-0.132794,-0.301325
Occupation_Manual,0.024769,0.011222,-0.014242,-0.213904,-0.379733,0.002230,-0.009819,-0.642032,-0.007747,-0.003504,...,-0.004262,-0.003504,-0.009665,-0.004955,0.009608,-0.269063,-0.203833,1.000000,-0.146827,-0.333169
Occupation_Professional,-0.022005,0.004709,0.028880,0.224440,0.203863,-0.004095,0.015569,0.608608,-0.002718,-0.002283,...,-0.003248,-0.002283,0.012473,0.033747,-0.015273,-0.175290,-0.132794,-0.146827,1.000000,-0.217054
Occupation_Skilled Manual,0.005141,-0.001308,-0.035670,-0.142416,-0.163579,-0.012811,-0.013929,-0.368936,0.024762,-0.005179,...,-0.001275,-0.005179,-0.016873,-0.007325,0.021074,-0.397754,-0.301325,-0.333169,-0.217054,1.000000